name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

jobs:
  now it is: 
    runs-on: ubuntu-20.04
    steps:
      - name: Run date
        run: |
          date


jobs:
  Directory contents: 
    runs-on: ubuntu-20.04
    steps:
      - name: directory contents
        run: |
          ls -l
