name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
    steps:
      - name: Run date
        run: |
          date
    steps:
      - name: directory contents
        run: |
          ls -l

